### ISSUE TITLE
OOP

### ISSUE THREAD

**Issue by Orinion** [InfiniteSoul/special-spoon#1]
isNumber sollte methode der Klasse Match sein :)
auch MatchToEquation (am besten dann nur  toEquation() nennen)
und macht aus equationToMatch einen konstruktor für Match.
Auch würde ich im Match keine feste Zahl einspeichern, viel mehr sollte es eine Methode 
int tozahl() geben, die überprüft ob die aktuelle zusammensetzung eine Valide zahl ist.
Bsp:

``` java
public int toInt()
{
    for(int i=0;i<10;i++)
    if(zahlCode == new Zahl(i).getZahlCode())
        return i;
    return -1;
}
```

Naja Viel Spaß noch, ihr müsst mein Konzept ja nicht verfolgen

**Comment by Mikerman** [comment]
Grrrrrr

**Comment by wbpascal** [comment]
Ich öffne das hier wieder Andrej du bist noch nicht vom Haken ( ≧Д≦)
