### ISSUE TITLE
Room implementation

### ISSUE THREAD

**Issue by Orinion** [InfiniteSoul/special-spoon#4]
Room ist noch nicht richtig implementiert, es wird benötigt für viele andere Sachen.
Mir würde es auch ein kurzes Implementationsdiagramm reichen.

[Room Klasse](https://github.com/InfiniteSoul/special-spoon/blob/master/MatchBox.Communication/src/de/matchbox/communication/shared/Room.java)

**Comment by wbpascal** [comment]
Ist alles schon geplant und jetzt lass uns unsere Arbeit machen und arbeite bitte mit deiner eigenen Gruppe xD
