### ISSUE TITLE
Tempus fugit

### ISSUE THREAD

**Issue by mschmidt98** [InfiniteSoul/special-spoon#7]
Nach Start des Spiels sollte nach einer gewissen Zeit (1-2 Minuten) das Spiel enden und dem Spieler keine Punkte zugespielt werden, falls dieser bis dahin keine Abgabe gemacht hat.
Das ganze sollte über einen ablaufenden Countdown oder eine ProgressBar im FrmMain visualisiert werden.

**Comment by mschmidt98** [comment]
Werde das später auf mich nehmen, das zu lösen :D

**Comment by wbpascal** [comment]
Ich würde vorschlagen das ganze mit dem Timer wieder zu entfernen, denn wenn jemand dem Raum beitritt hätte er mehr Zeit und wäre mit den anderen nicht mehr synchron. Eine andere Lösung wäre eine, die über den Server läuft, aber ich glaube nicht, dass wir noch genug Zeit für die Implementation haben.
