### ISSUE TITLE
Ablauf der Zeit

### ISSUE THREAD

**Issue by mschmidt98** [InfiniteSoul/special-spoon#9]
Ist die Zeit auf 0 abgelaufen, wirft der Server beim ersten Anfordern einer neuen Gleichung einen Fehler, ab dem zweiten Mal funktioniert es wieder. Wird während des Spiels eine neue angefordert, tritt der Fehler nicht auf.

**Comment by wbpascal** [comment]
Der Error passiert immer zufällig deshalb muss ich noch gucken woran das liegt.
